name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run package
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        input:
          - name: nixpkgs
            repo: nixpkgs
            owner: NixOS

          - name: pre-commit-hooks
            repo: pre-commit-hooks.nix
            owner: cachix
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: test
        uses: ./
        id: test
        with:
          input: ${{ matrix.input.name }}

      - name: check owner
        env:
          STEP_OWNER: ${{ steps.test.outputs.owner }}
          MATRIX_OWNER: ${{ matrix.input.owner }}
        run: if [ "$STEP_OWNER" != "$MATRIX_OWNER" ]; then exit 1; fi

      - name: check repo
        env:
          STEP_REPO: ${{ steps.test.outputs.repo }}
          MATRIX_REPO: ${{ matrix.input.repo }}
        run: if [ "$STEP_REPO" != "$MATRIX_REPO" ]; then exit 1; fi

      - name: check rev
        env:
          STEP_REV: ${{ steps.test.outputs.rev }}
        run: if [ -z "$STEP_REV" ]; then exit 1; fi

      - name: check short-rev
        env:
          STEP_SHORT_REV: ${{ steps.test.outputs.short-rev }}
        run: if [ -z "$STEP_SHORT_REV" ]; then exit 1; fi
  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16

      - uses: cycjimmy/semantic-release-action@5982a02995853159735cb838992248c4f0f16166 # v2.7.0
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
